import './styles.css';
import { INTENTIONS, REPORT_TYPES, SYSTEMS } from '../lib/aethos/constants';
import { createJournalEntry } from '../lib/aethos/journal';
import { validateBirthIntake, normalizeBirthLocationInput } from '../lib/aethos/profile';
import { generateAethosReport } from '../lib/aethos/reports';
import { addJournalEntry, addReport, clearLocalAethosState, getStorageMode, loadLocalAethosState, saveLocalAethosState, upsertIntake } from '../lib/aethos/storage';
import { createDemoIntelligenceSnapshot } from '../lib/aethos/intelligence/demo-core';
import { runNarrativeOrchestrator } from '../lib/aethos/narrative/orchestrator';
import { exportAethosData, deleteLocalAethosData, deleteProfileData, getActiveStorageMode, saveBirthIntake, saveNatalChart, saveProfile, saveTimingWindows } from '../lib/aethos/storage/storage-router';
import type { AethosState, BirthIntake, JournalTheme, ReportType, SymbolicSystem, UserIntention } from '../lib/aethos/types';
import type { EmaJournalEntry } from '../lib/aethos/journal/journal-types';

let state: AethosState = loadLocalAethosState();
const routes = ['/', '/onboarding', '/dashboard', '/profile', '/journal', '/reports', '/methodology', '/settings', '/privacy', '/academy', '/engine', '/timing-lab', '/divination-lab', '/learn', '/workshops', '/symbolic-profile', '/glossary', '/auth/reset'];

function navigate(path: string): void { history.pushState(null, '', path); render(); }
function persist(next: AethosState): void { state = next; saveLocalAethosState(state); render(); }
function card(title: string, body: string, badge = ''): string { return `<article class="card">${badge ? `<span class="badge gold">${badge}</span>` : ''}<h3>${title}</h3><p class="muted">${body}</p></article>`; }
function responsibleNote(): string { return `<div class="note"><strong>Responsible use.</strong> Aethos supports reflection, planning, and self-knowledge. It does not provide medical, legal, financial, psychiatric, emergency advice, commands, or guarantees.</div>`; }
function emaEntries(): EmaJournalEntry[] { return state.journalEntries.map((entry) => ({ id: `ema-${entry.id}`, mood: entry.mood, stress: entry.theme === 'decision' ? 7 : 5, focus: 6, sleepQuality: 6, socialConnection: entry.theme === 'relationship' ? 7 : 5, conflictLevel: entry.theme === 'relationship' ? 6 : 4, creativity: entry.theme === 'identity' ? 7 : 5, decisionPressure: entry.theme === 'decision' ? 8 : 4, bodyEnergy: 6, clarity: 5, freeText: entry.body, tags: entry.extractedThemes, linkedTimingWindowIds: [], createdAt: entry.createdAt, updatedAt: entry.createdAt })); }
function intelligence() { return createDemoIntelligenceSnapshot(state.profile!, emaEntries()); }
function pageHeader(kicker: string, title: string, copy: string): string { return `<section class="section"><span class="eyebrow">${kicker}</span><h2>${title}</h2><p class="lead">${copy}</p></section>`; }

function landing(): string {
  return `<section class="hero"><span class="eyebrow">Mystic Sage / Aethos</span><h1>Identity and timing intelligence for reflective self-knowledge.</h1><p class="lead">Aethos turns symbolic systems, reflective writing, and timing cycles into a structured self-knowledge workspace designed for interpretation, not fatalism.</p><div class="row"><button class="btn primary" data-nav="/onboarding">Begin onboarding</button><button class="btn" data-nav="/dashboard">View dashboard</button></div></section><section class="grid">${card('What Aethos does','Maps identity patterns, timing windows, journal themes, decisions, and reports into one coherent profile.','Platform')}${card('Core modules','Onboarding, dashboard, profile, journal, timing context, reports, methodology, and settings.','MVP')}${card('How it works','Aethos uses deterministic local generators now and is ready for Supabase and chart-engine integration later.','Architecture')}</section><section class="section"><h2>Responsible symbolic intelligence</h2><p class="muted">A timing window is not a command. It is a context marker for reflection and decision-making. Confidence levels describe interpretive strength, source clarity, and user-confirmed relevance.</p>${responsibleNote()}</section>`;
}

function onboarding(): string {
  const systems = SYSTEMS.map((s) => `<label><input type="checkbox" name="systems" value="${s.value}" ${['western-astrology','human-design','numerology','journaling'].includes(s.value) ? 'checked' : ''}/> ${s.label} <span class="badge">${s.status}</span></label>`).join('');
  return `${pageHeader('Onboarding','Build your Aethos intake','Your intake can be stored locally in this browser. If Supabase is configured, this form is ready for persistence integration without exposing secrets.')}<form id="intake" class="section stack"><div class="grid two"><label>Display name<input name="displayName" required value="${state.intake?.displayName ?? ''}" /></label><label>Birth date<input type="date" name="birthDate" required value="${state.intake?.birthDate ?? ''}" /></label><label>Birth time<input type="time" name="birthTime" value="${state.intake?.birthTime ?? ''}" /></label><label class="row"><input type="checkbox" name="birthTimeUnknown" ${state.intake?.birthTimeUnknown ? 'checked' : ''}/> Unknown birth time</label><label>Birth location<input name="birthLocation" required value="${state.intake?.birthLocation ?? ''}" /></label><label>Current location / timezone optional<input name="currentLocation" value="${state.intake?.currentLocation ?? ''}" /></label><label>Primary intention<select name="intention">${INTENTIONS.map((i) => `<option value="${i.value}" ${state.intake?.intention === i.value ? 'selected' : ''}>${i.label}</option>`).join('')}</select></label></div><div class="card"><h3>Preferred systems</h3><div class="grid two">${systems}</div></div><button class="btn primary" type="submit">Save intake and generate profile</button><p id="intake-errors" class="danger"></p></form>`;
}

function dashboard(): string {
  const profile = state.profile!;
  const core = intelligence();
  const active = core.windows[0];
  return `${pageHeader('Dashboard',`Welcome, ${profile.displayName}`,'A calm overview of timing intelligence, calibration, journal patterns, reports, and next reflection.')}<div class="grid">${card('Current Timing Window', active ? `${active.interpretiveSummary}<br>Start ${active.startDate} · Peak ${active.peakDate} · End ${active.endDate}` : 'No active timing window.', active ? `${Math.round(active.intensityScore * 100)}% intensity` : 'Learning')}${card('Personal Calibration', core.calibration.summary, core.calibration.status)}${card('Today’s Reflection', active?.suggestedReflection ?? profile.reflectionPrompts[0] ?? 'What evidence supports this interpretation?', 'Prompt')}${card('Upcoming Windows', core.windows.slice(0,3).map((w) => `${w.primaryTheme}: ${w.peakDate}`).join('<br>') || 'No upcoming windows.', 'Next 3')}${card('Data Mode', getStorageMode() === 'local' ? 'Local demo mode: data is stored in this browser only.' : 'Supabase mode configured.', getStorageMode())}</div>${responsibleNote()}`;
}

function profilePage(): string { const p = state.profile!; const core = intelligence(); return `${pageHeader('Profile', p.isSample ? 'Sample symbolic profile' : `${p.displayName}'s symbolic profile`, p.identitySummary)}<div class="note">${core.natalChart.dataQualityNotes.join(' ')}</div><div class="grid two">${card('Natal Intelligence Summary', core.natalChart.isDemo ? 'Demo calculation mode. Future production should use a server-side Swiss Ephemeris provider.' : 'Server calculation mode.', core.natalChart.calculationMode)}${card('Dominant Theme Scores', core.patternMap.map((item) => `${item.theme}: ${item.score}`).join('<br>'), 'Pattern map')}${card('Current Calibration Status', core.calibration.summary, core.calibration.status)}${['corePatterns','strengths','growthEdges','timingSensitivities','reflectionPrompts'].map((key) => `<section class="card"><h3>${key.replace(/([A-Z])/g,' $1')}</h3><ul>${(p[key as keyof typeof p] as string[]).map((x) => `<li>${x}</li>`).join('')}</ul></section>`).join('')}</div>`; }

function journal(): string {
  const entries = state.journalEntries.map((e) => `<article class="card"><span class="badge">Mood ${e.mood}/10 · ${e.theme}</span><p>${e.body}</p>${e.decisionContext ? `<p class="muted">Decision context: ${e.decisionContext}</p>` : ''}<p class="muted">Themes: ${e.extractedThemes.join(', ')}</p></article>`).join('') || `<div class="card"><h3>No entries yet</h3><p class="muted">Your journal gives Aethos a grounded record of lived experience, so insight does not depend on symbolism alone.</p></div>`;
  return `${pageHeader('Journal','Reflective pattern tracking','Create local entries with mood, theme, optional decision context, and lightweight theme extraction.')}<form id="journal" class="section stack"><div class="grid two"><label>Mood<input type="number" name="mood" min="1" max="10" value="6" /></label><label>Theme<select name="theme">${['identity','timing','decision','relationship','work','health-adjacent','practice'].map((x) => `<option value="${x}">${x}</option>`).join('')}</select></label></div><label>Decision context optional<input name="decisionContext" /></label><label>Entry<textarea name="body" required placeholder="What happened? What pattern do you notice? What evidence supports or challenges the interpretation?"></textarea></label><button class="btn primary">Save journal entry</button></form><section class="grid two">${entries}</section>`;
}

function reports(): string { const p = state.profile!; const core = intelligence(); const narrative = runNarrativeOrchestrator({ profile: p, windows: core.windows, journalEntries: emaEntries(), dataMode: getStorageMode(), calculationMode: core.natalChart.calculationMode }); const cards = REPORT_TYPES.map((r) => `<article class="card"><h3>${r.label}</h3><p class="muted">${r.description}</p><button class="btn primary" data-report="${r.value}">Generate</button></article>`).join('') + card('Lab Mode Export','Copy or inspect narrative scratchpad JSON from the deterministic orchestrator scaffold.','JSON'); const previews = state.reports.map((r) => `<article class="card"><span class="badge">${r.generatedAt}</span><h3>${r.title}</h3><pre>${r.markdown}</pre></article>`).join('') || `<article class="card"><h3>Narrative service preview</h3><pre>${narrative.markdown}</pre><pre>${JSON.stringify(narrative.json, null, 2)}</pre></article>`; return `${pageHeader('Reports',`${p.displayName}: intelligence reports`,'Generate reports with timing windows, journal calibration, theme scores, confidence notes, and responsible-use language.')}<section class="grid">${cards}</section><section class="section"><h2>Generated previews</h2><div class="stack">${previews}</div></section>`; }

function timingLab(): string { const core = intelligence(); const active = core.windows[0]; const eventRows = core.transitEvents.map((event) => `<tr><td>${event.transitBody}</td><td>${event.natalTarget}</td><td>${event.aspect.type}</td><td>${event.orb}°</td><td>${event.exactDate}</td><td>${event.rationale}</td></tr>`).join(''); return `${pageHeader('Timing Lab','Symbolic analytics cockpit','Aethos generates event windows, not absolute predictions. Demo mode uses deterministic sample ephemeris data.')}<div class="grid two">${card('Active Window', active ? active.interpretiveSummary : 'No active window.', active ? `${Math.round(active.confidenceScore * 100)}% confidence` : 'Learning')}${card('Personal Calibration', core.calibration.summary, core.calibration.status)}${card('Action Experiment', active?.recommendedActionExperiment ?? 'observe', 'Experiment')}${card('Lab Mode Transparency', JSON.stringify({ calculationMode: core.natalChart.calculationMode, demo: core.natalChart.isDemo, windows: core.windows.length }, null, 2), 'Raw')}</div><section class="section"><h2>Event Source Table</h2><table><thead><tr><th>Transit</th><th>Natal target</th><th>Aspect</th><th>Orb</th><th>Exact date</th><th>Theme contribution</th></tr></thead><tbody>${eventRows}</tbody></table></section>${responsibleNote()}`; }

function methodology(): string { return `${pageHeader('Methodology','Interpretation without fatalism','Aethos organizes symbolic lenses, timing windows, confidence, and lived journal evidence into a structured self-knowledge workspace.')}<div class="grid two">${card('What Aethos measures','Birth-intake metadata, selected symbolic lenses, reflective journal themes, timing windows, report context, and user-confirmed relevance.')}${card('What Aethos does not claim','No fate claims, diagnoses, financial forecasts, legal advice, medical advice, psychiatric advice, or guaranteed predictions.')}${card('V1 systems','Western astrology, Human Design, Numerology, and journaling/self-knowledge pattern tracking.')}${card('Confidence levels','Confidence describes source clarity, interpretive strength, and lived-evidence support. It is not certainty.')}${card('Data ethics','Local mode stores data in this browser only. Supabase mode must use public anon keys and Row Level Security.')}${card('Interpretive limits','Symbolic language is useful when it remains testable, humane, and agency-preserving.')}</div>${responsibleNote()}`; }

function settings(): string { const core = intelligence(); return `${pageHeader('Settings','Data mode, calculation mode, and privacy controls','Aethos can run in local demo mode without Supabase and provides export/delete workflows without dark-pattern retention.')}<section class="grid two">${card('Active storage mode', getActiveStorageMode() === 'local' ? 'Local mode: data is stored in this browser only. Clearing browser storage may delete it.' : 'Supabase mode: project database storage is configured. Production requires auth and RLS.', getActiveStorageMode())}${card('Calculation mode', core.natalChart.isDemo ? 'Demo ephemeris provider active. Outputs are deterministic samples, not astronomical calculations.' : 'Server provider configured.', core.natalChart.calculationMode)}${card('Sensitive data notice','Birth date/time/location, journal entries, timing windows, and reports are sensitive reflective records.')} ${card('Supabase status', getStorageMode() === 'local' ? 'Supabase public env vars are not configured.' : 'Supabase public env vars are configured; never expose service-role keys.', getStorageMode())}</section><section class="section stack"><div class="row"><button class="btn" id="export">Export my Aethos data</button><button class="btn" id="delete-profile">Clear local profile and birth data</button><button class="btn" id="clear">Delete all local Aethos data</button></div><textarea id="export-output" readonly placeholder="Export JSON appears here."></textarea>${responsibleNote()}</section>`; }
function privacy(): string { return `${pageHeader('Privacy','Data rights and sensitive records','Designed to support export and deletion workflows. This is not a claim of legal compliance.')}<div class="grid two">${card('Local mode','Data stays in this browser only; clearing browser storage may delete it.')} ${card('Supabase mode','Data is stored in the project database. Production requires authentication and Row Level Security policies.')} ${card('Export/delete','Use Settings to export JSON, clear profile/birth data, or delete all local Aethos data.')} ${card('Sensitive data','Birth facts, journal entries, timing windows, and reports should be treated as sensitive personal records.')}</div>${responsibleNote()}`; }

function placeholder(name: string): string { return `${pageHeader('Research module', name, 'This secondary route is stabilized as a coherent placeholder. Full production behavior is deferred behind the MVP routes.')}<div class="card"><p class="muted">No blank page. No unsupported claims. This module should only be expanded after deterministic data contracts and responsible-use language are ready.</p></div>`; }

function currentContent(): string { const path = location.pathname; if (path === '/') return landing(); if (path === '/onboarding') return onboarding(); if (path === '/dashboard') return dashboard(); if (path === '/profile' || path === '/symbolic-profile') return profilePage(); if (path === '/journal') return journal(); if (path === '/reports') return reports(); if (path === '/timing-lab') return timingLab(); if (path === '/methodology') return methodology(); if (path === '/settings') return settings(); if (path === '/privacy') return privacy(); if (routes.includes(path)) return placeholder(path); return placeholder('Route not found'); }

function render(): void {
  document.querySelector<HTMLDivElement>('#app')!.innerHTML = `<div class="shell"><nav class="nav"><a class="brand" data-nav="/">AETHOS</a><div class="links">${['/','/onboarding','/dashboard','/profile','/journal','/reports','/timing-lab','/methodology','/settings','/privacy'].map((r) => `<a class="${location.pathname===r?'active':''}" data-nav="${r}">${r === '/' ? 'Home' : r.slice(1)}</a>`).join('')}</div><button class="btn mobile" data-nav="/dashboard">Menu</button></nav><main class="main">${currentContent()}</main><footer class="footer">Aethos by Mystic Sage · symbolic intelligence for reflection, not fatalism · ${getStorageMode()} mode</footer></div>`;
  wireEvents();
}

function wireEvents(): void {
  document.querySelectorAll<HTMLElement>('[data-nav]').forEach((el) => el.onclick = () => navigate(el.dataset.nav!));
  document.querySelector<HTMLFormElement>('#intake')?.addEventListener('submit', (event) => { event.preventDefault(); const form = new FormData(event.currentTarget as HTMLFormElement); const intake: BirthIntake = { displayName: String(form.get('displayName') ?? ''), birthDate: String(form.get('birthDate') ?? ''), birthTime: String(form.get('birthTime') ?? ''), birthTimeUnknown: form.get('birthTimeUnknown') === 'on', birthLocation: normalizeBirthLocationInput(String(form.get('birthLocation') ?? '')), currentLocation: normalizeBirthLocationInput(String(form.get('currentLocation') ?? '')), intention: String(form.get('intention')) as UserIntention, preferredSystems: form.getAll('systems') as SymbolicSystem[], createdAt: new Date().toISOString() }; const errors = validateBirthIntake(intake); if (errors.length) { document.querySelector('#intake-errors')!.textContent = errors.join(' '); return; } const next = upsertIntake(state, intake); const core = createDemoIntelligenceSnapshot(next.profile!, emaEntries()); saveBirthIntake(intake); saveProfile(next.profile!); saveNatalChart(core.natalChart); saveTimingWindows(core.windows); persist(next); navigate('/dashboard'); });
  document.querySelector<HTMLFormElement>('#journal')?.addEventListener('submit', (event) => { event.preventDefault(); const form = new FormData(event.currentTarget as HTMLFormElement); const entry = createJournalEntry({ mood: Number(form.get('mood') ?? 6), theme: String(form.get('theme')) as JournalTheme, decisionContext: String(form.get('decisionContext') ?? ''), body: String(form.get('body') ?? '') }); persist(addJournalEntry(state, entry)); });
  document.querySelectorAll<HTMLElement>('[data-report]').forEach((el) => el.onclick = () => persist(addReport(state, generateAethosReport(el.dataset.report as ReportType, state.profile!, state.journalEntries, state.timingWindows))));
  document.querySelector<HTMLButtonElement>('#export')?.addEventListener('click', () => { const out = document.querySelector<HTMLTextAreaElement>('#export-output'); if (out) out.value = exportAethosData(); });
  document.querySelector<HTMLButtonElement>('#delete-profile')?.addEventListener('click', () => { deleteProfileData(); persist(clearLocalAethosState()); });
  document.querySelector<HTMLButtonElement>('#clear')?.addEventListener('click', () => { deleteLocalAethosData(); persist(clearLocalAethosState()); });
}

window.addEventListener('popstate', render);
render();
