import './styles.css';
import { INTENTIONS, REPORT_TYPES, SYSTEMS } from '../lib/aethos/constants';
import { createJournalEntry } from '../lib/aethos/journal';
import { validateBirthIntake, normalizeBirthLocationInput } from '../lib/aethos/profile';
import { generateAethosReport } from '../lib/aethos/reports';
import { addJournalEntry, addReport, clearLocalAethosState, getStorageMode, loadLocalAethosState, saveLocalAethosState, upsertIntake } from '../lib/aethos/storage';
import type { AethosState, BirthIntake, JournalTheme, ReportType, SymbolicSystem, UserIntention } from '../lib/aethos/types';

let state: AethosState = loadLocalAethosState();
const routes = ['/', '/onboarding', '/dashboard', '/profile', '/journal', '/reports', '/methodology', '/settings', '/academy', '/engine', '/timing-lab', '/divination-lab', '/learn', '/workshops', '/symbolic-profile', '/glossary', '/auth/reset'];

function navigate(path: string): void { history.pushState(null, '', path); render(); }
function persist(next: AethosState): void { state = next; saveLocalAethosState(state); render(); }
function card(title: string, body: string, badge = ''): string { return `<article class="card">${badge ? `<span class="badge gold">${badge}</span>` : ''}<h3>${title}</h3><p class="muted">${body}</p></article>`; }
function responsibleNote(): string { return `<div class="note"><strong>Responsible use.</strong> Aethos supports reflection and decision context. It does not provide medical, legal, financial, psychiatric, or guaranteed predictive advice.</div>`; }
function pageHeader(kicker: string, title: string, copy: string): string { return `<section class="section"><span class="eyebrow">${kicker}</span><h2>${title}</h2><p class="lead">${copy}</p></section>`; }

function landing(): string {
  return `<section class="hero"><span class="eyebrow">Mystic Sage / Aethos</span><h1>Identity and timing intelligence for reflective self-knowledge.</h1><p class="lead">Aethos turns symbolic systems, reflective writing, and timing cycles into a structured self-knowledge workspace designed for interpretation, not fatalism.</p><div class="row"><button class="btn primary" data-nav="/onboarding">Begin onboarding</button><button class="btn" data-nav="/dashboard">View dashboard</button></div></section><section class="grid">${card('What Aethos does','Maps identity patterns, timing windows, journal themes, decisions, and reports into one coherent profile.','Platform')}${card('Core modules','Onboarding, dashboard, profile, journal, timing context, reports, methodology, and settings.','MVP')}${card('How it works','Aethos uses deterministic local generators now and is ready for Supabase and chart-engine integration later.','Architecture')}</section><section class="section"><h2>Responsible symbolic intelligence</h2><p class="muted">A timing window is not a command. It is a context marker for reflection and decision-making. Confidence levels describe interpretive strength, source clarity, and user-confirmed relevance.</p>${responsibleNote()}</section>`;
}

function onboarding(): string {
  const systems = SYSTEMS.map((s) => `<label><input type="checkbox" name="systems" value="${s.value}" ${['western-astrology','human-design','numerology','journaling'].includes(s.value) ? 'checked' : ''}/> ${s.label} <span class="badge">${s.status}</span></label>`).join('');
  return `${pageHeader('Onboarding','Build your Aethos intake','Your intake can be stored locally in this browser. If Supabase is configured, this form is ready for persistence integration without exposing secrets.')}<form id="intake" class="section stack"><div class="grid two"><label>Display name<input name="displayName" required value="${state.intake?.displayName ?? ''}" /></label><label>Birth date<input type="date" name="birthDate" required value="${state.intake?.birthDate ?? ''}" /></label><label>Birth time<input type="time" name="birthTime" value="${state.intake?.birthTime ?? ''}" /></label><label class="row"><input type="checkbox" name="birthTimeUnknown" ${state.intake?.birthTimeUnknown ? 'checked' : ''}/> Unknown birth time</label><label>Birth location<input name="birthLocation" required value="${state.intake?.birthLocation ?? ''}" /></label><label>Current location / timezone optional<input name="currentLocation" value="${state.intake?.currentLocation ?? ''}" /></label><label>Primary intention<select name="intention">${INTENTIONS.map((i) => `<option value="${i.value}" ${state.intake?.intention === i.value ? 'selected' : ''}>${i.label}</option>`).join('')}</select></label></div><div class="card"><h3>Preferred systems</h3><div class="grid two">${systems}</div></div><button class="btn primary" type="submit">Save intake and generate profile</button><p id="intake-errors" class="danger"></p></form>`;
}

function dashboard(): string {
  const profile = state.profile!;
  return `${pageHeader('Dashboard',`Welcome, ${profile.displayName}`,'A calm overview of your profile, timing context, journal patterns, reports, and next reflection.')}<div class="grid">${card('Aethos Core', profile.identitySummary, profile.isSample ? 'Sample profile' : 'Active')}${card('Current Timing', state.timingWindows[0]?.summary ?? 'No timing windows yet.', state.timingWindows[0]?.confidence ?? 'sample')}${card('Journal Pattern Signals', state.journalEntries.length ? `${state.journalEntries.length} entries recorded.` : 'No journal entries yet. Begin with one grounded observation.', 'Journal')}${card('Recent Reports', state.reports.length ? `${state.reports.length} reports generated.` : 'Generate your first structured brief.', 'Reports')}${card('Next Recommended Reflection', profile.reflectionPrompts[0] ?? 'What evidence supports this interpretation?', 'Prompt')}</div>${responsibleNote()}`;
}

function profilePage(): string { const p = state.profile!; return `${pageHeader('Profile', p.isSample ? 'Sample symbolic profile' : `${p.displayName}'s symbolic profile`, p.identitySummary)}<div class="grid two">${['corePatterns','strengths','growthEdges','timingSensitivities','reflectionPrompts'].map((key) => `<section class="card"><h3>${key.replace(/([A-Z])/g,' $1')}</h3><ul>${(p[key as keyof typeof p] as string[]).map((x) => `<li>${x}</li>`).join('')}</ul></section>`).join('')}</div>`; }

function journal(): string {
  const entries = state.journalEntries.map((e) => `<article class="card"><span class="badge">Mood ${e.mood}/10 · ${e.theme}</span><p>${e.body}</p>${e.decisionContext ? `<p class="muted">Decision context: ${e.decisionContext}</p>` : ''}<p class="muted">Themes: ${e.extractedThemes.join(', ')}</p></article>`).join('') || `<div class="card"><h3>No entries yet</h3><p class="muted">Your journal gives Aethos a grounded record of lived experience, so insight does not depend on symbolism alone.</p></div>`;
  return `${pageHeader('Journal','Reflective pattern tracking','Create local entries with mood, theme, optional decision context, and lightweight theme extraction.')}<form id="journal" class="section stack"><div class="grid two"><label>Mood<input type="number" name="mood" min="1" max="10" value="6" /></label><label>Theme<select name="theme">${['identity','timing','decision','relationship','work','health-adjacent','practice'].map((x) => `<option value="${x}">${x}</option>`).join('')}</select></label></div><label>Decision context optional<input name="decisionContext" /></label><label>Entry<textarea name="body" required placeholder="What happened? What pattern do you notice? What evidence supports or challenges the interpretation?"></textarea></label><button class="btn primary">Save journal entry</button></form><section class="grid two">${entries}</section>`;
}

function reports(): string { const p = state.profile!; const cards = REPORT_TYPES.map((r) => `<article class="card"><h3>${r.label}</h3><p class="muted">${r.description}</p><button class="btn primary" data-report="${r.value}">Generate</button></article>`).join(''); const previews = state.reports.map((r) => `<article class="card"><span class="badge">${r.generatedAt}</span><h3>${r.title}</h3><pre>${r.markdown}</pre></article>`).join('') || card('No reports yet','Generate a structured report from available profile, timing, and journal data.'); return `${pageHeader('Reports',`${p.displayName}: structured reports`,'Generate clean Markdown/HTML-ready previews. PDF export is intentionally deferred until a renderer is selected.')}<section class="grid">${cards}</section><section class="section"><h2>Generated previews</h2><div class="stack">${previews}</div></section>`; }

function methodology(): string { return `${pageHeader('Methodology','Interpretation without fatalism','Aethos organizes symbolic lenses, timing windows, confidence, and lived journal evidence into a structured self-knowledge workspace.')}<div class="grid two">${card('What Aethos measures','Birth-intake metadata, selected symbolic lenses, reflective journal themes, timing windows, report context, and user-confirmed relevance.')}${card('What Aethos does not claim','No fate claims, diagnoses, financial forecasts, legal advice, medical advice, psychiatric advice, or guaranteed predictions.')}${card('V1 systems','Western astrology, Human Design, Numerology, and journaling/self-knowledge pattern tracking.')}${card('Confidence levels','Confidence describes source clarity, interpretive strength, and lived-evidence support. It is not certainty.')}${card('Data ethics','Local mode stores data in this browser only. Supabase mode must use public anon keys and Row Level Security.')}${card('Interpretive limits','Symbolic language is useful when it remains testable, humane, and agency-preserving.')}</div>${responsibleNote()}`; }

function settings(): string { return `${pageHeader('Settings','Data mode and privacy','Aethos can run in local demo mode without Supabase.')}<section class="grid two">${card('Current data mode', getStorageMode() === 'local' ? 'Local mode: data is stored in this browser only.' : 'Supabase mode: public client variables are configured.', getStorageMode())}${card('Privacy posture','Do not enter emergency, clinical, legal, or highly sensitive data. Export/delete controls should be expanded before production accounts.')}</section><section class="section stack"><button class="btn" id="clear">Clear/reset local data</button><p class="muted">Theme preference is currently managed by the system dark visual identity.</p></section>`; }

function placeholder(name: string): string { return `${pageHeader('Research module', name, 'This secondary route is stabilized as a coherent placeholder. Full production behavior is deferred behind the MVP routes.')}<div class="card"><p class="muted">No blank page. No unsupported claims. This module should only be expanded after deterministic data contracts and responsible-use language are ready.</p></div>`; }

function currentContent(): string { const path = location.pathname; if (path === '/') return landing(); if (path === '/onboarding') return onboarding(); if (path === '/dashboard') return dashboard(); if (path === '/profile' || path === '/symbolic-profile') return profilePage(); if (path === '/journal') return journal(); if (path === '/reports') return reports(); if (path === '/methodology') return methodology(); if (path === '/settings') return settings(); if (routes.includes(path)) return placeholder(path); return placeholder('Route not found'); }

function render(): void {
  document.querySelector<HTMLDivElement>('#app')!.innerHTML = `<div class="shell"><nav class="nav"><a class="brand" data-nav="/">AETHOS</a><div class="links">${['/','/onboarding','/dashboard','/profile','/journal','/reports','/methodology','/settings'].map((r) => `<a class="${location.pathname===r?'active':''}" data-nav="${r}">${r === '/' ? 'Home' : r.slice(1)}</a>`).join('')}</div><button class="btn mobile" data-nav="/dashboard">Menu</button></nav><main class="main">${currentContent()}</main><footer class="footer">Aethos by Mystic Sage · symbolic intelligence for reflection, not fatalism · ${getStorageMode()} mode</footer></div>`;
  wireEvents();
}

function wireEvents(): void {
  document.querySelectorAll<HTMLElement>('[data-nav]').forEach((el) => el.onclick = () => navigate(el.dataset.nav!));
  document.querySelector<HTMLFormElement>('#intake')?.addEventListener('submit', (event) => { event.preventDefault(); const form = new FormData(event.currentTarget as HTMLFormElement); const intake: BirthIntake = { displayName: String(form.get('displayName') ?? ''), birthDate: String(form.get('birthDate') ?? ''), birthTime: String(form.get('birthTime') ?? ''), birthTimeUnknown: form.get('birthTimeUnknown') === 'on', birthLocation: normalizeBirthLocationInput(String(form.get('birthLocation') ?? '')), currentLocation: normalizeBirthLocationInput(String(form.get('currentLocation') ?? '')), intention: String(form.get('intention')) as UserIntention, preferredSystems: form.getAll('systems') as SymbolicSystem[], createdAt: new Date().toISOString() }; const errors = validateBirthIntake(intake); if (errors.length) { document.querySelector('#intake-errors')!.textContent = errors.join(' '); return; } persist(upsertIntake(state, intake)); navigate('/dashboard'); });
  document.querySelector<HTMLFormElement>('#journal')?.addEventListener('submit', (event) => { event.preventDefault(); const form = new FormData(event.currentTarget as HTMLFormElement); const entry = createJournalEntry({ mood: Number(form.get('mood') ?? 6), theme: String(form.get('theme')) as JournalTheme, decisionContext: String(form.get('decisionContext') ?? ''), body: String(form.get('body') ?? '') }); persist(addJournalEntry(state, entry)); });
  document.querySelectorAll<HTMLElement>('[data-report]').forEach((el) => el.onclick = () => persist(addReport(state, generateAethosReport(el.dataset.report as ReportType, state.profile!, state.journalEntries, state.timingWindows))));
  document.querySelector<HTMLButtonElement>('#clear')?.addEventListener('click', () => persist(clearLocalAethosState()));
}

window.addEventListener('popstate', render);
render();
